#!/usr/bin/env bash
# Pushes app/ to the VM tofu provisioned and (re)starts the stack.
# Safe to re-run any time you change litellm-config.yaml, Caddyfile, or .env.
set -euo pipefail
cd "$(dirname "$0")"

if [ ! -f app/.env ]; then
  echo "app/.env not found. Copy app/.env.example to app/.env and fill in real values first." >&2
  exit 1
fi

IP=$(tofu -chdir=infra output -raw public_ip)
echo "Target: root@${IP}"

ssh -o StrictHostKeyChecking=accept-new root@"${IP}" "mkdir -p /opt/app /opt/data"
rsync -avz --exclude '.env' --exclude 'docker-compose.override.yml' --exclude 'team-credentials.txt' app/ root@"${IP}":/opt/app/
scp app/.env root@"${IP}":/opt/app/.env
# data/ is a sibling of app/, not inside it — Open WebUI's jupyter service
# mounts it via a relative ../data, which resolves to /opt/data here,
# matching the local repo-root/app + repo-root/data layout.
rsync -avz data/ root@"${IP}":/opt/data/
# boltdiy is now a custom-built image (Dockerfile.boltdiy), not pulled from
# a registry — `--build` rebuilds it from whatever's in patches/ on every
# deploy; `up -d` still pulls the other services' images as before.
ssh root@"${IP}" "cd /opt/app && docker compose up -d --build"

echo
echo "Deployed. Once DNS for your domain points at ${IP}:"
echo "  LiteLLM gateway:    https://gateway.<your-domain>"
echo "  bolt.diy:           https://build{1..5}.<your-domain> (team0 = organizer only, see below)"
echo "  DeepSeek Harness:   https://team{1..5}.<your-domain>   (team0 = organizer only, see below)"
echo "  Open WebUI:         https://analyze.<your-domain>"
echo
echo "team0 (organizer testing) isn't started by the command above — see"
echo "docker-compose.yml's 'organizer' profile note. Basic Auth credentials"
echo "for every team live in app/team-credentials.txt (generated by"
echo "scripts/generate-team-auth.sh, gitignored, not pushed by this script)."
